#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Contains a custom HTTP header named X-Served-By.

apt-get update
apt-get install -y nginx


printf %s "server {
    add_header X-Served-By $HOSTNAME;

}" > /etc/nginx/sites-available/default

service nginx restart
