#!/usr/bin/env bash
# install and configures the load balancer
# enables management via the init script.
# Distributes requests using a round-robin algorithm.

sudo apt-get install -yhaproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 59637-web-01 54.236.17.236:80 check
    server 59637-web-02 54.162.94.221:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
