#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself 


trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done

