#!/usr/bin/env bash
#Bash script that displays, The content of the current directory
#In a list format Where only the part of the name after
#the first dash is displayed

for file in *
do

    if [[ $file != .* ]]
    then
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)

        echo "$name_after_dash"
    fi
done
