#!/usr/bin/env bash
#Bash script that gives you information about the school file

file="school"

if [ -e "$file" ]
then
    echo "$file file exists"

    if [ -s "$file" ]
    then
        echo "$file file is not empty"

        if [ -f "$file" ]
	then
            echo "$file is a regular file"
        else
            :
        fi
    else
        echo "$file file is empty"
    fi
else
    echo "$file file does not exist"
fi
